Updated core dependency.
membraneframework/membrane_stream_plugin pull request #2
Opened 2022-11-18 09:55 UTC by shuntrho

2022-11-18 14:19 UTC, FelonEkonom approved these changes

2022-11-18 16:53 UTC, varsill requested changes

2022-11-18 16:53 UTC, varsill commented on test/serializer_test.exs
> +  alias Membrane.{Buffer, ChildrenSpec, RemoteStream, Testing.Pipeline}
ChildrenSpec alias is not used

2022-11-18 16:53 UTC, varsill commented on test/serializer_test.exs
> +        assert {[], state} = Serializer.handle_init(%{}, %Serializer{version: unquote(version)})
You could use `nil` as a first argument of the `Serializer.handle_init/2` invocation, just as in the invocation below

2022-11-18 16:53 UTC, varsill commented on test/support/testing_source.ex
> +  def handle_info(:supply_demand, _ctx, %{actions: [action | actions]} = state) do
It should be `handle_info`, since we are sending `:supply_demand` with a plain `Kernel.send/2`. (just a few lines above, the TestingSource sends that message to itself inside the `handle_demand` callback)

2022-11-24 10:32 UTC, varsill approved these changes

2022-11-28 13:04 UTC, merged